// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CLogin.proto

package network.message;

public final class CLogin {
  private CLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.message.LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <code>required int64 ttp = 2;</code>
     */
    boolean hasTtp();
    /**
     * <code>required int64 ttp = 2;</code>
     */
    long getTtp();

    /**
     * <code>required string token = 3;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 3;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>required string udid = 4;</code>
     */
    boolean hasUdid();
    /**
     * <code>required string udid = 4;</code>
     */
    java.lang.String getUdid();
    /**
     * <code>required string udid = 4;</code>
     */
    com.google.protobuf.ByteString
        getUdidBytes();

    /**
     * <code>required string userName = 5;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 5;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>required int32 accountType = 6;</code>
     */
    boolean hasAccountType();
    /**
     * <code>required int32 accountType = 6;</code>
     */
    int getAccountType();

    /**
     * <code>required int32 serverId = 7;</code>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 7;</code>
     */
    int getServerId();

    /**
     * <code>required string version = 8;</code>
     */
    boolean hasVersion();
    /**
     * <code>required string version = 8;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>required string version = 8;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>optional string uid6w = 9;</code>
     */
    boolean hasUid6W();
    /**
     * <code>optional string uid6w = 9;</code>
     */
    java.lang.String getUid6W();
    /**
     * <code>optional string uid6w = 9;</code>
     */
    com.google.protobuf.ByteString
        getUid6WBytes();
  }
  /**
   * Protobuf type {@code network.message.LoginRequest}
   *
   * <pre>
   ** User登录请求 
   * </pre>
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.message.LoginRequest)
      LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginRequest defaultInstance;
    public static LoginRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ttp_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              token_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              udid_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              userName_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              accountType_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              serverId_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              version_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              uid6W_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.CLogin.internal_static_network_message_LoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.CLogin.internal_static_network_message_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.CLogin.LoginRequest.class, network.message.CLogin.LoginRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginRequest> PARSER =
        new com.google.protobuf.AbstractParser<LoginRequest>() {
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int TTP_FIELD_NUMBER = 2;
    private long ttp_;
    /**
     * <code>required int64 ttp = 2;</code>
     */
    public boolean hasTtp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 ttp = 2;</code>
     */
    public long getTtp() {
      return ttp_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private java.lang.Object token_;
    /**
     * <code>required string token = 3;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string token = 3;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UDID_FIELD_NUMBER = 4;
    private java.lang.Object udid_;
    /**
     * <code>required string udid = 4;</code>
     */
    public boolean hasUdid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string udid = 4;</code>
     */
    public java.lang.String getUdid() {
      java.lang.Object ref = udid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          udid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string udid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 5;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string userName = 5;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTTYPE_FIELD_NUMBER = 6;
    private int accountType_;
    /**
     * <code>required int32 accountType = 6;</code>
     */
    public boolean hasAccountType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 accountType = 6;</code>
     */
    public int getAccountType() {
      return accountType_;
    }

    public static final int SERVERID_FIELD_NUMBER = 7;
    private int serverId_;
    /**
     * <code>required int32 serverId = 7;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 serverId = 7;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int VERSION_FIELD_NUMBER = 8;
    private java.lang.Object version_;
    /**
     * <code>required string version = 8;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string version = 8;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string version = 8;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID6W_FIELD_NUMBER = 9;
    private java.lang.Object uid6W_;
    /**
     * <code>optional string uid6w = 9;</code>
     */
    public boolean hasUid6W() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string uid6w = 9;</code>
     */
    public java.lang.String getUid6W() {
      java.lang.Object ref = uid6W_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid6W_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uid6w = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUid6WBytes() {
      java.lang.Object ref = uid6W_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid6W_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uid_ = 0L;
      ttp_ = 0L;
      token_ = "";
      udid_ = "";
      userName_ = "";
      accountType_ = 0;
      serverId_ = 0;
      version_ = "";
      uid6W_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTtp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUdid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, ttp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUdidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, accountType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, serverId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getUid6WBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ttp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUdidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, accountType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, serverId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getVersionBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getUid6WBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static network.message.CLogin.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CLogin.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CLogin.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CLogin.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CLogin.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CLogin.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.CLogin.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.CLogin.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.CLogin.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CLogin.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(network.message.CLogin.LoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.message.LoginRequest}
     *
     * <pre>
     ** User登录请求 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.message.LoginRequest)
        network.message.CLogin.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.CLogin.internal_static_network_message_LoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.CLogin.internal_static_network_message_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.CLogin.LoginRequest.class, network.message.CLogin.LoginRequest.Builder.class);
      }

      // Construct using network.message.CLogin.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        ttp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        udid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        accountType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        uid6W_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.CLogin.internal_static_network_message_LoginRequest_descriptor;
      }

      public network.message.CLogin.LoginRequest getDefaultInstanceForType() {
        return network.message.CLogin.LoginRequest.getDefaultInstance();
      }

      public network.message.CLogin.LoginRequest build() {
        network.message.CLogin.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.CLogin.LoginRequest buildPartial() {
        network.message.CLogin.LoginRequest result = new network.message.CLogin.LoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ttp_ = ttp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.udid_ = udid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.accountType_ = accountType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.uid6W_ = uid6W_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.CLogin.LoginRequest) {
          return mergeFrom((network.message.CLogin.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.CLogin.LoginRequest other) {
        if (other == network.message.CLogin.LoginRequest.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasTtp()) {
          setTtp(other.getTtp());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000004;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasUdid()) {
          bitField0_ |= 0x00000008;
          udid_ = other.udid_;
          onChanged();
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000010;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasAccountType()) {
          setAccountType(other.getAccountType());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000080;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasUid6W()) {
          bitField0_ |= 0x00000100;
          uid6W_ = other.uid6W_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasTtp()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        if (!hasUdid()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        if (!hasAccountType()) {
          
          return false;
        }
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.CLogin.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.CLogin.LoginRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private long ttp_ ;
      /**
       * <code>required int64 ttp = 2;</code>
       */
      public boolean hasTtp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 ttp = 2;</code>
       */
      public long getTtp() {
        return ttp_;
      }
      /**
       * <code>required int64 ttp = 2;</code>
       */
      public Builder setTtp(long value) {
        bitField0_ |= 0x00000002;
        ttp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ttp = 2;</code>
       */
      public Builder clearTtp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ttp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 3;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string token = 3;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 3;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 3;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object udid_ = "";
      /**
       * <code>required string udid = 4;</code>
       */
      public boolean hasUdid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string udid = 4;</code>
       */
      public java.lang.String getUdid() {
        java.lang.Object ref = udid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            udid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string udid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUdidBytes() {
        java.lang.Object ref = udid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          udid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string udid = 4;</code>
       */
      public Builder setUdid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        udid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string udid = 4;</code>
       */
      public Builder clearUdid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        udid_ = getDefaultInstance().getUdid();
        onChanged();
        return this;
      }
      /**
       * <code>required string udid = 4;</code>
       */
      public Builder setUdidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        udid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 5;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string userName = 5;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 5;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 5;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 5;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userName_ = value;
        onChanged();
        return this;
      }

      private int accountType_ ;
      /**
       * <code>required int32 accountType = 6;</code>
       */
      public boolean hasAccountType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 accountType = 6;</code>
       */
      public int getAccountType() {
        return accountType_;
      }
      /**
       * <code>required int32 accountType = 6;</code>
       */
      public Builder setAccountType(int value) {
        bitField0_ |= 0x00000020;
        accountType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountType = 6;</code>
       */
      public Builder clearAccountType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        accountType_ = 0;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <code>required int32 serverId = 7;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 serverId = 7;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 7;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000040;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 7;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>required string version = 8;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string version = 8;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string version = 8;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string version = 8;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 8;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string version = 8;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uid6W_ = "";
      /**
       * <code>optional string uid6w = 9;</code>
       */
      public boolean hasUid6W() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string uid6w = 9;</code>
       */
      public java.lang.String getUid6W() {
        java.lang.Object ref = uid6W_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uid6W_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uid6w = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUid6WBytes() {
        java.lang.Object ref = uid6W_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid6W_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uid6w = 9;</code>
       */
      public Builder setUid6W(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        uid6W_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid6w = 9;</code>
       */
      public Builder clearUid6W() {
        bitField0_ = (bitField0_ & ~0x00000100);
        uid6W_ = getDefaultInstance().getUid6W();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uid6w = 9;</code>
       */
      public Builder setUid6WBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        uid6W_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:network.message.LoginRequest)
    }

    static {
      defaultInstance = new LoginRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:network.message.LoginRequest)
  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.message.LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    network.message.ResultInfo.Result getResult();

    /**
     * <code>optional .network.message.UserInfo userInfo = 2;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>optional .network.message.UserInfo userInfo = 2;</code>
     */
    network.message.CUserInfo.UserInfo getUserInfo();
    /**
     * <code>optional .network.message.UserInfo userInfo = 2;</code>
     */
    network.message.CUserInfo.UserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * Protobuf type {@code network.message.LoginResponse}
   *
   * <pre>
   ** User登录回应 
   * </pre>
   */
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.message.LoginResponse)
      LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginResponse defaultInstance;
    public static LoginResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LoginResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              network.message.ResultInfo.Result value = network.message.ResultInfo.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                result_ = value;
              }
              break;
            }
            case 18: {
              network.message.CUserInfo.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(network.message.CUserInfo.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.CLogin.internal_static_network_message_LoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.CLogin.internal_static_network_message_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.CLogin.LoginResponse.class, network.message.CLogin.LoginResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginResponse> PARSER =
        new com.google.protobuf.AbstractParser<LoginResponse>() {
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private network.message.ResultInfo.Result result_;
    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    public network.message.ResultInfo.Result getResult() {
      return result_;
    }

    public static final int USERINFO_FIELD_NUMBER = 2;
    private network.message.CUserInfo.UserInfo userInfo_;
    /**
     * <code>optional .network.message.UserInfo userInfo = 2;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .network.message.UserInfo userInfo = 2;</code>
     */
    public network.message.CUserInfo.UserInfo getUserInfo() {
      return userInfo_;
    }
    /**
     * <code>optional .network.message.UserInfo userInfo = 2;</code>
     */
    public network.message.CUserInfo.UserInfoOrBuilder getUserInfoOrBuilder() {
      return userInfo_;
    }

    private void initFields() {
      result_ = network.message.ResultInfo.Result.SUCCESS;
      userInfo_ = network.message.CUserInfo.UserInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUserInfo()) {
        if (!getUserInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, userInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, userInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static network.message.CLogin.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CLogin.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CLogin.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CLogin.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CLogin.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CLogin.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.CLogin.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.CLogin.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.CLogin.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CLogin.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(network.message.CLogin.LoginResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.message.LoginResponse}
     *
     * <pre>
     ** User登录回应 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.message.LoginResponse)
        network.message.CLogin.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.CLogin.internal_static_network_message_LoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.CLogin.internal_static_network_message_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.CLogin.LoginResponse.class, network.message.CLogin.LoginResponse.Builder.class);
      }

      // Construct using network.message.CLogin.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = network.message.ResultInfo.Result.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userInfoBuilder_ == null) {
          userInfo_ = network.message.CUserInfo.UserInfo.getDefaultInstance();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.CLogin.internal_static_network_message_LoginResponse_descriptor;
      }

      public network.message.CLogin.LoginResponse getDefaultInstanceForType() {
        return network.message.CLogin.LoginResponse.getDefaultInstance();
      }

      public network.message.CLogin.LoginResponse build() {
        network.message.CLogin.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.CLogin.LoginResponse buildPartial() {
        network.message.CLogin.LoginResponse result = new network.message.CLogin.LoginResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.CLogin.LoginResponse) {
          return mergeFrom((network.message.CLogin.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.CLogin.LoginResponse other) {
        if (other == network.message.CLogin.LoginResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (hasUserInfo()) {
          if (!getUserInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.CLogin.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.CLogin.LoginResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private network.message.ResultInfo.Result result_ = network.message.ResultInfo.Result.SUCCESS;
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public network.message.ResultInfo.Result getResult() {
        return result_;
      }
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public Builder setResult(network.message.ResultInfo.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = network.message.ResultInfo.Result.SUCCESS;
        onChanged();
        return this;
      }

      private network.message.CUserInfo.UserInfo userInfo_ = network.message.CUserInfo.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          network.message.CUserInfo.UserInfo, network.message.CUserInfo.UserInfo.Builder, network.message.CUserInfo.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public network.message.CUserInfo.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public Builder setUserInfo(network.message.CUserInfo.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public Builder setUserInfo(
          network.message.CUserInfo.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public Builder mergeUserInfo(network.message.CUserInfo.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              userInfo_ != network.message.CUserInfo.UserInfo.getDefaultInstance()) {
            userInfo_ =
              network.message.CUserInfo.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = network.message.CUserInfo.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public network.message.CUserInfo.UserInfo.Builder getUserInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      public network.message.CUserInfo.UserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_;
        }
      }
      /**
       * <code>optional .network.message.UserInfo userInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.CUserInfo.UserInfo, network.message.CUserInfo.UserInfo.Builder, network.message.CUserInfo.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.CUserInfo.UserInfo, network.message.CUserInfo.UserInfo.Builder, network.message.CUserInfo.UserInfoOrBuilder>(
                  getUserInfo(),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:network.message.LoginResponse)
    }

    static {
      defaultInstance = new LoginResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:network.message.LoginResponse)
  }

  public interface KickNtfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.message.KickNtf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    network.message.ResultInfo.Result getResult();
  }
  /**
   * Protobuf type {@code network.message.KickNtf}
   *
   * <pre>
   ** 踢User 下线  Result（重复登录或服务器关闭）
   * </pre>
   */
  public static final class KickNtf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.message.KickNtf)
      KickNtfOrBuilder {
    // Use KickNtf.newBuilder() to construct.
    private KickNtf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KickNtf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KickNtf defaultInstance;
    public static KickNtf getDefaultInstance() {
      return defaultInstance;
    }

    public KickNtf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KickNtf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              network.message.ResultInfo.Result value = network.message.ResultInfo.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                result_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.CLogin.internal_static_network_message_KickNtf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.CLogin.internal_static_network_message_KickNtf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.CLogin.KickNtf.class, network.message.CLogin.KickNtf.Builder.class);
    }

    public static com.google.protobuf.Parser<KickNtf> PARSER =
        new com.google.protobuf.AbstractParser<KickNtf>() {
      public KickNtf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KickNtf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KickNtf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private network.message.ResultInfo.Result result_;
    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .network.message.Result result = 1;</code>
     */
    public network.message.ResultInfo.Result getResult() {
      return result_;
    }

    private void initFields() {
      result_ = network.message.ResultInfo.Result.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, result_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static network.message.CLogin.KickNtf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CLogin.KickNtf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CLogin.KickNtf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CLogin.KickNtf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CLogin.KickNtf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CLogin.KickNtf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.CLogin.KickNtf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.CLogin.KickNtf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.CLogin.KickNtf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CLogin.KickNtf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(network.message.CLogin.KickNtf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.message.KickNtf}
     *
     * <pre>
     ** 踢User 下线  Result（重复登录或服务器关闭）
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.message.KickNtf)
        network.message.CLogin.KickNtfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.CLogin.internal_static_network_message_KickNtf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.CLogin.internal_static_network_message_KickNtf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.CLogin.KickNtf.class, network.message.CLogin.KickNtf.Builder.class);
      }

      // Construct using network.message.CLogin.KickNtf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = network.message.ResultInfo.Result.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.CLogin.internal_static_network_message_KickNtf_descriptor;
      }

      public network.message.CLogin.KickNtf getDefaultInstanceForType() {
        return network.message.CLogin.KickNtf.getDefaultInstance();
      }

      public network.message.CLogin.KickNtf build() {
        network.message.CLogin.KickNtf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.CLogin.KickNtf buildPartial() {
        network.message.CLogin.KickNtf result = new network.message.CLogin.KickNtf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.CLogin.KickNtf) {
          return mergeFrom((network.message.CLogin.KickNtf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.CLogin.KickNtf other) {
        if (other == network.message.CLogin.KickNtf.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.CLogin.KickNtf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.CLogin.KickNtf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private network.message.ResultInfo.Result result_ = network.message.ResultInfo.Result.SUCCESS;
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public network.message.ResultInfo.Result getResult() {
        return result_;
      }
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public Builder setResult(network.message.ResultInfo.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .network.message.Result result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = network.message.ResultInfo.Result.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:network.message.KickNtf)
    }

    static {
      defaultInstance = new KickNtf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:network.message.KickNtf)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_message_LoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_message_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_message_LoginResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_message_LoginResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_message_KickNtf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_message_KickNtf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014CLogin.proto\022\017network.message\032\020ResultI" +
      "nfo.proto\032\017CUserInfo.proto\"\236\001\n\014LoginRequ" +
      "est\022\013\n\003uid\030\001 \002(\003\022\013\n\003ttp\030\002 \002(\003\022\r\n\005token\030\003" +
      " \002(\t\022\014\n\004udid\030\004 \002(\t\022\020\n\010userName\030\005 \002(\t\022\023\n\013" +
      "accountType\030\006 \002(\005\022\020\n\010serverId\030\007 \002(\005\022\017\n\007v" +
      "ersion\030\010 \002(\t\022\r\n\005uid6w\030\t \001(\t\"e\n\rLoginResp" +
      "onse\022\'\n\006result\030\001 \002(\0162\027.network.message.R" +
      "esult\022+\n\010userInfo\030\002 \001(\0132\031.network.messag" +
      "e.UserInfo\"2\n\007KickNtf\022\'\n\006result\030\001 \002(\0162\027." +
      "network.message.Result"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          network.message.ResultInfo.getDescriptor(),
          network.message.CUserInfo.getDescriptor(),
        }, assigner);
    internal_static_network_message_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_network_message_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_message_LoginRequest_descriptor,
        new java.lang.String[] { "Uid", "Ttp", "Token", "Udid", "UserName", "AccountType", "ServerId", "Version", "Uid6W", });
    internal_static_network_message_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_network_message_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_message_LoginResponse_descriptor,
        new java.lang.String[] { "Result", "UserInfo", });
    internal_static_network_message_KickNtf_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_network_message_KickNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_message_KickNtf_descriptor,
        new java.lang.String[] { "Result", });
    network.message.ResultInfo.getDescriptor();
    network.message.CUserInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
