// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CUserInfo.proto

package network.message;

public final class CUserInfo {
  private CUserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.message.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <code>required int32 locationServerId = 2;</code>
     */
    boolean hasLocationServerId();
    /**
     * <code>required int32 locationServerId = 2;</code>
     */
    int getLocationServerId();

    /**
     * <code>required int32 homeServerId = 3;</code>
     */
    boolean hasHomeServerId();
    /**
     * <code>required int32 homeServerId = 3;</code>
     */
    int getHomeServerId();

    /**
     * <code>required string name = 4;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 level = 5;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 5;</code>
     */
    int getLevel();

    /**
     * <code>required int32 icon = 6;</code>
     */
    boolean hasIcon();
    /**
     * <code>required int32 icon = 6;</code>
     */
    int getIcon();

    /**
     * <code>required int64 power = 7;</code>
     */
    boolean hasPower();
    /**
     * <code>required int64 power = 7;</code>
     */
    long getPower();

    /**
     * <code>required int64 killCount = 8;</code>
     */
    boolean hasKillCount();
    /**
     * <code>required int64 killCount = 8;</code>
     */
    long getKillCount();

    /**
     * <code>required int32 powerRank = 10;</code>
     *
     * <pre>
     *	required Pst pst = 9;
     * </pre>
     */
    boolean hasPowerRank();
    /**
     * <code>required int32 powerRank = 10;</code>
     *
     * <pre>
     *	required Pst pst = 9;
     * </pre>
     */
    int getPowerRank();

    /**
     * <code>required int32 vip = 11;</code>
     */
    boolean hasVip();
    /**
     * <code>required int32 vip = 11;</code>
     */
    int getVip();

    /**
     * <code>required string jid = 13;</code>
     *
     * <pre>
     *	repeated MapTitleInfo title = 12;
     * </pre>
     */
    boolean hasJid();
    /**
     * <code>required string jid = 13;</code>
     *
     * <pre>
     *	repeated MapTitleInfo title = 12;
     * </pre>
     */
    java.lang.String getJid();
    /**
     * <code>required string jid = 13;</code>
     *
     * <pre>
     *	repeated MapTitleInfo title = 12;
     * </pre>
     */
    com.google.protobuf.ByteString
        getJidBytes();

    /**
     * <code>required string sign = 16;</code>
     *
     * <pre>
     *required int32 likeNum = 14;
     *required bool isLike = 15;
     * </pre>
     */
    boolean hasSign();
    /**
     * <code>required string sign = 16;</code>
     *
     * <pre>
     *required int32 likeNum = 14;
     *required bool isLike = 15;
     * </pre>
     */
    java.lang.String getSign();
    /**
     * <code>required string sign = 16;</code>
     *
     * <pre>
     *required int32 likeNum = 14;
     *required bool isLike = 15;
     * </pre>
     */
    com.google.protobuf.ByteString
        getSignBytes();

    /**
     * <code>required string avatar = 17;</code>
     */
    boolean hasAvatar();
    /**
     * <code>required string avatar = 17;</code>
     */
    java.lang.String getAvatar();
    /**
     * <code>required string avatar = 17;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <code>required int32 lang = 18;</code>
     */
    boolean hasLang();
    /**
     * <code>required int32 lang = 18;</code>
     */
    int getLang();

    /**
     * <code>required int32 nationalFlag = 19;</code>
     */
    boolean hasNationalFlag();
    /**
     * <code>required int32 nationalFlag = 19;</code>
     */
    int getNationalFlag();

    /**
     * <code>required bool newRole = 21;</code>
     *
     * <pre>
     *required int32 bitFlag = 20;
     * </pre>
     */
    boolean hasNewRole();
    /**
     * <code>required bool newRole = 21;</code>
     *
     * <pre>
     *required int32 bitFlag = 20;
     * </pre>
     */
    boolean getNewRole();
  }
  /**
   * Protobuf type {@code network.message.UserInfo}
   *
   * <pre>
   ** User Info 
   * </pre>
   */
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.message.UserInfo)
      UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserInfo defaultInstance;
    public static UserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public UserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              locationServerId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              homeServerId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              name_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              icon_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              power_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              killCount_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000100;
              powerRank_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000200;
              vip_ = input.readInt32();
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              jid_ = bs;
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              sign_ = bs;
              break;
            }
            case 138: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              avatar_ = bs;
              break;
            }
            case 144: {
              bitField0_ |= 0x00002000;
              lang_ = input.readInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00004000;
              nationalFlag_ = input.readInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00008000;
              newRole_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.CUserInfo.internal_static_network_message_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.CUserInfo.internal_static_network_message_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.CUserInfo.UserInfo.class, network.message.CUserInfo.UserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<UserInfo> PARSER =
        new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int LOCATIONSERVERID_FIELD_NUMBER = 2;
    private int locationServerId_;
    /**
     * <code>required int32 locationServerId = 2;</code>
     */
    public boolean hasLocationServerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 locationServerId = 2;</code>
     */
    public int getLocationServerId() {
      return locationServerId_;
    }

    public static final int HOMESERVERID_FIELD_NUMBER = 3;
    private int homeServerId_;
    /**
     * <code>required int32 homeServerId = 3;</code>
     */
    public boolean hasHomeServerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 homeServerId = 3;</code>
     */
    public int getHomeServerId() {
      return homeServerId_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    /**
     * <code>required string name = 4;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    /**
     * <code>required int32 level = 5;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 level = 5;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int ICON_FIELD_NUMBER = 6;
    private int icon_;
    /**
     * <code>required int32 icon = 6;</code>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 icon = 6;</code>
     */
    public int getIcon() {
      return icon_;
    }

    public static final int POWER_FIELD_NUMBER = 7;
    private long power_;
    /**
     * <code>required int64 power = 7;</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int64 power = 7;</code>
     */
    public long getPower() {
      return power_;
    }

    public static final int KILLCOUNT_FIELD_NUMBER = 8;
    private long killCount_;
    /**
     * <code>required int64 killCount = 8;</code>
     */
    public boolean hasKillCount() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 killCount = 8;</code>
     */
    public long getKillCount() {
      return killCount_;
    }

    public static final int POWERRANK_FIELD_NUMBER = 10;
    private int powerRank_;
    /**
     * <code>required int32 powerRank = 10;</code>
     *
     * <pre>
     *	required Pst pst = 9;
     * </pre>
     */
    public boolean hasPowerRank() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 powerRank = 10;</code>
     *
     * <pre>
     *	required Pst pst = 9;
     * </pre>
     */
    public int getPowerRank() {
      return powerRank_;
    }

    public static final int VIP_FIELD_NUMBER = 11;
    private int vip_;
    /**
     * <code>required int32 vip = 11;</code>
     */
    public boolean hasVip() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 vip = 11;</code>
     */
    public int getVip() {
      return vip_;
    }

    public static final int JID_FIELD_NUMBER = 13;
    private java.lang.Object jid_;
    /**
     * <code>required string jid = 13;</code>
     *
     * <pre>
     *	repeated MapTitleInfo title = 12;
     * </pre>
     */
    public boolean hasJid() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string jid = 13;</code>
     *
     * <pre>
     *	repeated MapTitleInfo title = 12;
     * </pre>
     */
    public java.lang.String getJid() {
      java.lang.Object ref = jid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string jid = 13;</code>
     *
     * <pre>
     *	repeated MapTitleInfo title = 12;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJidBytes() {
      java.lang.Object ref = jid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGN_FIELD_NUMBER = 16;
    private java.lang.Object sign_;
    /**
     * <code>required string sign = 16;</code>
     *
     * <pre>
     *required int32 likeNum = 14;
     *required bool isLike = 15;
     * </pre>
     */
    public boolean hasSign() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string sign = 16;</code>
     *
     * <pre>
     *required int32 likeNum = 14;
     *required bool isLike = 15;
     * </pre>
     */
    public java.lang.String getSign() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sign = 16;</code>
     *
     * <pre>
     *required int32 likeNum = 14;
     *required bool isLike = 15;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      java.lang.Object ref = sign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 17;
    private java.lang.Object avatar_;
    /**
     * <code>required string avatar = 17;</code>
     */
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required string avatar = 17;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          avatar_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string avatar = 17;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANG_FIELD_NUMBER = 18;
    private int lang_;
    /**
     * <code>required int32 lang = 18;</code>
     */
    public boolean hasLang() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int32 lang = 18;</code>
     */
    public int getLang() {
      return lang_;
    }

    public static final int NATIONALFLAG_FIELD_NUMBER = 19;
    private int nationalFlag_;
    /**
     * <code>required int32 nationalFlag = 19;</code>
     */
    public boolean hasNationalFlag() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required int32 nationalFlag = 19;</code>
     */
    public int getNationalFlag() {
      return nationalFlag_;
    }

    public static final int NEWROLE_FIELD_NUMBER = 21;
    private boolean newRole_;
    /**
     * <code>required bool newRole = 21;</code>
     *
     * <pre>
     *required int32 bitFlag = 20;
     * </pre>
     */
    public boolean hasNewRole() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required bool newRole = 21;</code>
     *
     * <pre>
     *required int32 bitFlag = 20;
     * </pre>
     */
    public boolean getNewRole() {
      return newRole_;
    }

    private void initFields() {
      uid_ = 0L;
      locationServerId_ = 0;
      homeServerId_ = 0;
      name_ = "";
      level_ = 0;
      icon_ = 0;
      power_ = 0L;
      killCount_ = 0L;
      powerRank_ = 0;
      vip_ = 0;
      jid_ = "";
      sign_ = "";
      avatar_ = "";
      lang_ = 0;
      nationalFlag_ = 0;
      newRole_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocationServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHomeServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKillCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPowerRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAvatar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLang()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNationalFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewRole()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, locationServerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, homeServerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, icon_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, power_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, killCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(10, powerRank_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(11, vip_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(13, getJidBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(16, getSignBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(17, getAvatarBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(18, lang_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(19, nationalFlag_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBool(21, newRole_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, locationServerId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, homeServerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, icon_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, power_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, killCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, powerRank_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, vip_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getJidBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getSignBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getAvatarBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, lang_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, nationalFlag_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(21, newRole_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static network.message.CUserInfo.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.CUserInfo.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.CUserInfo.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CUserInfo.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(network.message.CUserInfo.UserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.message.UserInfo}
     *
     * <pre>
     ** User Info 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.message.UserInfo)
        network.message.CUserInfo.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.CUserInfo.internal_static_network_message_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.CUserInfo.internal_static_network_message_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.CUserInfo.UserInfo.class, network.message.CUserInfo.UserInfo.Builder.class);
      }

      // Construct using network.message.CUserInfo.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        locationServerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        homeServerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        icon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        power_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        killCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        powerRank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        vip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        jid_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        sign_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        avatar_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        lang_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        nationalFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        newRole_ = false;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.CUserInfo.internal_static_network_message_UserInfo_descriptor;
      }

      public network.message.CUserInfo.UserInfo getDefaultInstanceForType() {
        return network.message.CUserInfo.UserInfo.getDefaultInstance();
      }

      public network.message.CUserInfo.UserInfo build() {
        network.message.CUserInfo.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.CUserInfo.UserInfo buildPartial() {
        network.message.CUserInfo.UserInfo result = new network.message.CUserInfo.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.locationServerId_ = locationServerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.homeServerId_ = homeServerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.icon_ = icon_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.power_ = power_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.killCount_ = killCount_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.powerRank_ = powerRank_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.vip_ = vip_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.jid_ = jid_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.sign_ = sign_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.avatar_ = avatar_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.lang_ = lang_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.nationalFlag_ = nationalFlag_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.newRole_ = newRole_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.CUserInfo.UserInfo) {
          return mergeFrom((network.message.CUserInfo.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.CUserInfo.UserInfo other) {
        if (other == network.message.CUserInfo.UserInfo.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasLocationServerId()) {
          setLocationServerId(other.getLocationServerId());
        }
        if (other.hasHomeServerId()) {
          setHomeServerId(other.getHomeServerId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        if (other.hasKillCount()) {
          setKillCount(other.getKillCount());
        }
        if (other.hasPowerRank()) {
          setPowerRank(other.getPowerRank());
        }
        if (other.hasVip()) {
          setVip(other.getVip());
        }
        if (other.hasJid()) {
          bitField0_ |= 0x00000400;
          jid_ = other.jid_;
          onChanged();
        }
        if (other.hasSign()) {
          bitField0_ |= 0x00000800;
          sign_ = other.sign_;
          onChanged();
        }
        if (other.hasAvatar()) {
          bitField0_ |= 0x00001000;
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.hasLang()) {
          setLang(other.getLang());
        }
        if (other.hasNationalFlag()) {
          setNationalFlag(other.getNationalFlag());
        }
        if (other.hasNewRole()) {
          setNewRole(other.getNewRole());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasLocationServerId()) {
          
          return false;
        }
        if (!hasHomeServerId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasIcon()) {
          
          return false;
        }
        if (!hasPower()) {
          
          return false;
        }
        if (!hasKillCount()) {
          
          return false;
        }
        if (!hasPowerRank()) {
          
          return false;
        }
        if (!hasVip()) {
          
          return false;
        }
        if (!hasJid()) {
          
          return false;
        }
        if (!hasSign()) {
          
          return false;
        }
        if (!hasAvatar()) {
          
          return false;
        }
        if (!hasLang()) {
          
          return false;
        }
        if (!hasNationalFlag()) {
          
          return false;
        }
        if (!hasNewRole()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.CUserInfo.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.CUserInfo.UserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private int locationServerId_ ;
      /**
       * <code>required int32 locationServerId = 2;</code>
       */
      public boolean hasLocationServerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 locationServerId = 2;</code>
       */
      public int getLocationServerId() {
        return locationServerId_;
      }
      /**
       * <code>required int32 locationServerId = 2;</code>
       */
      public Builder setLocationServerId(int value) {
        bitField0_ |= 0x00000002;
        locationServerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 locationServerId = 2;</code>
       */
      public Builder clearLocationServerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        locationServerId_ = 0;
        onChanged();
        return this;
      }

      private int homeServerId_ ;
      /**
       * <code>required int32 homeServerId = 3;</code>
       */
      public boolean hasHomeServerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 homeServerId = 3;</code>
       */
      public int getHomeServerId() {
        return homeServerId_;
      }
      /**
       * <code>required int32 homeServerId = 3;</code>
       */
      public Builder setHomeServerId(int value) {
        bitField0_ |= 0x00000004;
        homeServerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 homeServerId = 3;</code>
       */
      public Builder clearHomeServerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        homeServerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 4;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 5;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }

      private int icon_ ;
      /**
       * <code>required int32 icon = 6;</code>
       */
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 icon = 6;</code>
       */
      public int getIcon() {
        return icon_;
      }
      /**
       * <code>required int32 icon = 6;</code>
       */
      public Builder setIcon(int value) {
        bitField0_ |= 0x00000020;
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 icon = 6;</code>
       */
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000020);
        icon_ = 0;
        onChanged();
        return this;
      }

      private long power_ ;
      /**
       * <code>required int64 power = 7;</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int64 power = 7;</code>
       */
      public long getPower() {
        return power_;
      }
      /**
       * <code>required int64 power = 7;</code>
       */
      public Builder setPower(long value) {
        bitField0_ |= 0x00000040;
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 power = 7;</code>
       */
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000040);
        power_ = 0L;
        onChanged();
        return this;
      }

      private long killCount_ ;
      /**
       * <code>required int64 killCount = 8;</code>
       */
      public boolean hasKillCount() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int64 killCount = 8;</code>
       */
      public long getKillCount() {
        return killCount_;
      }
      /**
       * <code>required int64 killCount = 8;</code>
       */
      public Builder setKillCount(long value) {
        bitField0_ |= 0x00000080;
        killCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 killCount = 8;</code>
       */
      public Builder clearKillCount() {
        bitField0_ = (bitField0_ & ~0x00000080);
        killCount_ = 0L;
        onChanged();
        return this;
      }

      private int powerRank_ ;
      /**
       * <code>required int32 powerRank = 10;</code>
       *
       * <pre>
       *	required Pst pst = 9;
       * </pre>
       */
      public boolean hasPowerRank() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 powerRank = 10;</code>
       *
       * <pre>
       *	required Pst pst = 9;
       * </pre>
       */
      public int getPowerRank() {
        return powerRank_;
      }
      /**
       * <code>required int32 powerRank = 10;</code>
       *
       * <pre>
       *	required Pst pst = 9;
       * </pre>
       */
      public Builder setPowerRank(int value) {
        bitField0_ |= 0x00000100;
        powerRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 powerRank = 10;</code>
       *
       * <pre>
       *	required Pst pst = 9;
       * </pre>
       */
      public Builder clearPowerRank() {
        bitField0_ = (bitField0_ & ~0x00000100);
        powerRank_ = 0;
        onChanged();
        return this;
      }

      private int vip_ ;
      /**
       * <code>required int32 vip = 11;</code>
       */
      public boolean hasVip() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 vip = 11;</code>
       */
      public int getVip() {
        return vip_;
      }
      /**
       * <code>required int32 vip = 11;</code>
       */
      public Builder setVip(int value) {
        bitField0_ |= 0x00000200;
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 vip = 11;</code>
       */
      public Builder clearVip() {
        bitField0_ = (bitField0_ & ~0x00000200);
        vip_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object jid_ = "";
      /**
       * <code>required string jid = 13;</code>
       *
       * <pre>
       *	repeated MapTitleInfo title = 12;
       * </pre>
       */
      public boolean hasJid() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string jid = 13;</code>
       *
       * <pre>
       *	repeated MapTitleInfo title = 12;
       * </pre>
       */
      public java.lang.String getJid() {
        java.lang.Object ref = jid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string jid = 13;</code>
       *
       * <pre>
       *	repeated MapTitleInfo title = 12;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getJidBytes() {
        java.lang.Object ref = jid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string jid = 13;</code>
       *
       * <pre>
       *	repeated MapTitleInfo title = 12;
       * </pre>
       */
      public Builder setJid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        jid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string jid = 13;</code>
       *
       * <pre>
       *	repeated MapTitleInfo title = 12;
       * </pre>
       */
      public Builder clearJid() {
        bitField0_ = (bitField0_ & ~0x00000400);
        jid_ = getDefaultInstance().getJid();
        onChanged();
        return this;
      }
      /**
       * <code>required string jid = 13;</code>
       *
       * <pre>
       *	repeated MapTitleInfo title = 12;
       * </pre>
       */
      public Builder setJidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        jid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sign_ = "";
      /**
       * <code>required string sign = 16;</code>
       *
       * <pre>
       *required int32 likeNum = 14;
       *required bool isLike = 15;
       * </pre>
       */
      public boolean hasSign() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string sign = 16;</code>
       *
       * <pre>
       *required int32 likeNum = 14;
       *required bool isLike = 15;
       * </pre>
       */
      public java.lang.String getSign() {
        java.lang.Object ref = sign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sign_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sign = 16;</code>
       *
       * <pre>
       *required int32 likeNum = 14;
       *required bool isLike = 15;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSignBytes() {
        java.lang.Object ref = sign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sign = 16;</code>
       *
       * <pre>
       *required int32 likeNum = 14;
       *required bool isLike = 15;
       * </pre>
       */
      public Builder setSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 16;</code>
       *
       * <pre>
       *required int32 likeNum = 14;
       *required bool isLike = 15;
       * </pre>
       */
      public Builder clearSign() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string sign = 16;</code>
       *
       * <pre>
       *required int32 likeNum = 14;
       *required bool isLike = 15;
       * </pre>
       */
      public Builder setSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        sign_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <code>required string avatar = 17;</code>
       */
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required string avatar = 17;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            avatar_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string avatar = 17;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string avatar = 17;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string avatar = 17;</code>
       */
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00001000);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <code>required string avatar = 17;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        avatar_ = value;
        onChanged();
        return this;
      }

      private int lang_ ;
      /**
       * <code>required int32 lang = 18;</code>
       */
      public boolean hasLang() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int32 lang = 18;</code>
       */
      public int getLang() {
        return lang_;
      }
      /**
       * <code>required int32 lang = 18;</code>
       */
      public Builder setLang(int value) {
        bitField0_ |= 0x00002000;
        lang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lang = 18;</code>
       */
      public Builder clearLang() {
        bitField0_ = (bitField0_ & ~0x00002000);
        lang_ = 0;
        onChanged();
        return this;
      }

      private int nationalFlag_ ;
      /**
       * <code>required int32 nationalFlag = 19;</code>
       */
      public boolean hasNationalFlag() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required int32 nationalFlag = 19;</code>
       */
      public int getNationalFlag() {
        return nationalFlag_;
      }
      /**
       * <code>required int32 nationalFlag = 19;</code>
       */
      public Builder setNationalFlag(int value) {
        bitField0_ |= 0x00004000;
        nationalFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nationalFlag = 19;</code>
       */
      public Builder clearNationalFlag() {
        bitField0_ = (bitField0_ & ~0x00004000);
        nationalFlag_ = 0;
        onChanged();
        return this;
      }

      private boolean newRole_ ;
      /**
       * <code>required bool newRole = 21;</code>
       *
       * <pre>
       *required int32 bitFlag = 20;
       * </pre>
       */
      public boolean hasNewRole() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required bool newRole = 21;</code>
       *
       * <pre>
       *required int32 bitFlag = 20;
       * </pre>
       */
      public boolean getNewRole() {
        return newRole_;
      }
      /**
       * <code>required bool newRole = 21;</code>
       *
       * <pre>
       *required int32 bitFlag = 20;
       * </pre>
       */
      public Builder setNewRole(boolean value) {
        bitField0_ |= 0x00008000;
        newRole_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool newRole = 21;</code>
       *
       * <pre>
       *required int32 bitFlag = 20;
       * </pre>
       */
      public Builder clearNewRole() {
        bitField0_ = (bitField0_ & ~0x00008000);
        newRole_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:network.message.UserInfo)
    }

    static {
      defaultInstance = new UserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:network.message.UserInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_message_UserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_message_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CUserInfo.proto\022\017network.message\"\224\002\n\010U" +
      "serInfo\022\013\n\003uid\030\001 \002(\003\022\030\n\020locationServerId" +
      "\030\002 \002(\005\022\024\n\014homeServerId\030\003 \002(\005\022\014\n\004name\030\004 \002" +
      "(\t\022\r\n\005level\030\005 \002(\005\022\014\n\004icon\030\006 \002(\005\022\r\n\005power" +
      "\030\007 \002(\003\022\021\n\tkillCount\030\010 \002(\003\022\021\n\tpowerRank\030\n" +
      " \002(\005\022\013\n\003vip\030\013 \002(\005\022\013\n\003jid\030\r \002(\t\022\014\n\004sign\030\020" +
      " \002(\t\022\016\n\006avatar\030\021 \002(\t\022\014\n\004lang\030\022 \002(\005\022\024\n\014na" +
      "tionalFlag\030\023 \002(\005\022\017\n\007newRole\030\025 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_network_message_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_network_message_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_message_UserInfo_descriptor,
        new java.lang.String[] { "Uid", "LocationServerId", "HomeServerId", "Name", "Level", "Icon", "Power", "KillCount", "PowerRank", "Vip", "Jid", "Sign", "Avatar", "Lang", "NationalFlag", "NewRole", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
