// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CVip.proto

package network.message;

public final class CVip {
  private CVip() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VipNtfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.message.VipNtf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .network.message.VipNtfInfo info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <code>required .network.message.VipNtfInfo info = 1;</code>
     */
    network.message.CVipInfo.VipNtfInfo getInfo();
    /**
     * <code>required .network.message.VipNtfInfo info = 1;</code>
     */
    network.message.CVipInfo.VipNtfInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code network.message.VipNtf}
   *
   * <pre>
   ** VIP 通知，(登录时,获得VIP时，VIP升级时，限时VIP结束时通知 )
   * </pre>
   */
  public static final class VipNtf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.message.VipNtf)
      VipNtfOrBuilder {
    // Use VipNtf.newBuilder() to construct.
    private VipNtf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VipNtf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VipNtf defaultInstance;
    public static VipNtf getDefaultInstance() {
      return defaultInstance;
    }

    public VipNtf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VipNtf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              network.message.CVipInfo.VipNtfInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(network.message.CVipInfo.VipNtfInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.CVip.internal_static_network_message_VipNtf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.CVip.internal_static_network_message_VipNtf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.CVip.VipNtf.class, network.message.CVip.VipNtf.Builder.class);
    }

    public static com.google.protobuf.Parser<VipNtf> PARSER =
        new com.google.protobuf.AbstractParser<VipNtf>() {
      public VipNtf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VipNtf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VipNtf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INFO_FIELD_NUMBER = 1;
    private network.message.CVipInfo.VipNtfInfo info_;
    /**
     * <code>required .network.message.VipNtfInfo info = 1;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .network.message.VipNtfInfo info = 1;</code>
     */
    public network.message.CVipInfo.VipNtfInfo getInfo() {
      return info_;
    }
    /**
     * <code>required .network.message.VipNtfInfo info = 1;</code>
     */
    public network.message.CVipInfo.VipNtfInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = network.message.CVipInfo.VipNtfInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static network.message.CVip.VipNtf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CVip.VipNtf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CVip.VipNtf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CVip.VipNtf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CVip.VipNtf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CVip.VipNtf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.CVip.VipNtf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.CVip.VipNtf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.CVip.VipNtf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CVip.VipNtf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(network.message.CVip.VipNtf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.message.VipNtf}
     *
     * <pre>
     ** VIP 通知，(登录时,获得VIP时，VIP升级时，限时VIP结束时通知 )
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.message.VipNtf)
        network.message.CVip.VipNtfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.CVip.internal_static_network_message_VipNtf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.CVip.internal_static_network_message_VipNtf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.CVip.VipNtf.class, network.message.CVip.VipNtf.Builder.class);
      }

      // Construct using network.message.CVip.VipNtf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = network.message.CVipInfo.VipNtfInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.CVip.internal_static_network_message_VipNtf_descriptor;
      }

      public network.message.CVip.VipNtf getDefaultInstanceForType() {
        return network.message.CVip.VipNtf.getDefaultInstance();
      }

      public network.message.CVip.VipNtf build() {
        network.message.CVip.VipNtf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.CVip.VipNtf buildPartial() {
        network.message.CVip.VipNtf result = new network.message.CVip.VipNtf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.CVip.VipNtf) {
          return mergeFrom((network.message.CVip.VipNtf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.CVip.VipNtf other) {
        if (other == network.message.CVip.VipNtf.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.CVip.VipNtf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.CVip.VipNtf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private network.message.CVipInfo.VipNtfInfo info_ = network.message.CVipInfo.VipNtfInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          network.message.CVipInfo.VipNtfInfo, network.message.CVipInfo.VipNtfInfo.Builder, network.message.CVipInfo.VipNtfInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public network.message.CVipInfo.VipNtfInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public Builder setInfo(network.message.CVipInfo.VipNtfInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public Builder setInfo(
          network.message.CVipInfo.VipNtfInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public Builder mergeInfo(network.message.CVipInfo.VipNtfInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != network.message.CVipInfo.VipNtfInfo.getDefaultInstance()) {
            info_ =
              network.message.CVipInfo.VipNtfInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = network.message.CVipInfo.VipNtfInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public network.message.CVipInfo.VipNtfInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      public network.message.CVipInfo.VipNtfInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>required .network.message.VipNtfInfo info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          network.message.CVipInfo.VipNtfInfo, network.message.CVipInfo.VipNtfInfo.Builder, network.message.CVipInfo.VipNtfInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              network.message.CVipInfo.VipNtfInfo, network.message.CVipInfo.VipNtfInfo.Builder, network.message.CVipInfo.VipNtfInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:network.message.VipNtf)
    }

    static {
      defaultInstance = new VipNtf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:network.message.VipNtf)
  }

  public interface VipLevelUpNtfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.message.VipLevelUpNtf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 currentLevel = 1;</code>
     *
     * <pre>
     ** 当前等级 
     * </pre>
     */
    boolean hasCurrentLevel();
    /**
     * <code>required int32 currentLevel = 1;</code>
     *
     * <pre>
     ** 当前等级 
     * </pre>
     */
    int getCurrentLevel();
  }
  /**
   * Protobuf type {@code network.message.VipLevelUpNtf}
   *
   * <pre>
   ** 升级通知 
   * </pre>
   */
  public static final class VipLevelUpNtf extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.message.VipLevelUpNtf)
      VipLevelUpNtfOrBuilder {
    // Use VipLevelUpNtf.newBuilder() to construct.
    private VipLevelUpNtf(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VipLevelUpNtf(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VipLevelUpNtf defaultInstance;
    public static VipLevelUpNtf getDefaultInstance() {
      return defaultInstance;
    }

    public VipLevelUpNtf getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VipLevelUpNtf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currentLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.message.CVip.internal_static_network_message_VipLevelUpNtf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.message.CVip.internal_static_network_message_VipLevelUpNtf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.message.CVip.VipLevelUpNtf.class, network.message.CVip.VipLevelUpNtf.Builder.class);
    }

    public static com.google.protobuf.Parser<VipLevelUpNtf> PARSER =
        new com.google.protobuf.AbstractParser<VipLevelUpNtf>() {
      public VipLevelUpNtf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VipLevelUpNtf(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VipLevelUpNtf> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CURRENTLEVEL_FIELD_NUMBER = 1;
    private int currentLevel_;
    /**
     * <code>required int32 currentLevel = 1;</code>
     *
     * <pre>
     ** 当前等级 
     * </pre>
     */
    public boolean hasCurrentLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 currentLevel = 1;</code>
     *
     * <pre>
     ** 当前等级 
     * </pre>
     */
    public int getCurrentLevel() {
      return currentLevel_;
    }

    private void initFields() {
      currentLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCurrentLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, currentLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, currentLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static network.message.CVip.VipLevelUpNtf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static network.message.CVip.VipLevelUpNtf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static network.message.CVip.VipLevelUpNtf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static network.message.CVip.VipLevelUpNtf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(network.message.CVip.VipLevelUpNtf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.message.VipLevelUpNtf}
     *
     * <pre>
     ** 升级通知 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.message.VipLevelUpNtf)
        network.message.CVip.VipLevelUpNtfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.message.CVip.internal_static_network_message_VipLevelUpNtf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.message.CVip.internal_static_network_message_VipLevelUpNtf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.message.CVip.VipLevelUpNtf.class, network.message.CVip.VipLevelUpNtf.Builder.class);
      }

      // Construct using network.message.CVip.VipLevelUpNtf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        currentLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.message.CVip.internal_static_network_message_VipLevelUpNtf_descriptor;
      }

      public network.message.CVip.VipLevelUpNtf getDefaultInstanceForType() {
        return network.message.CVip.VipLevelUpNtf.getDefaultInstance();
      }

      public network.message.CVip.VipLevelUpNtf build() {
        network.message.CVip.VipLevelUpNtf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.message.CVip.VipLevelUpNtf buildPartial() {
        network.message.CVip.VipLevelUpNtf result = new network.message.CVip.VipLevelUpNtf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentLevel_ = currentLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.message.CVip.VipLevelUpNtf) {
          return mergeFrom((network.message.CVip.VipLevelUpNtf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.message.CVip.VipLevelUpNtf other) {
        if (other == network.message.CVip.VipLevelUpNtf.getDefaultInstance()) return this;
        if (other.hasCurrentLevel()) {
          setCurrentLevel(other.getCurrentLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCurrentLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.message.CVip.VipLevelUpNtf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.message.CVip.VipLevelUpNtf) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int currentLevel_ ;
      /**
       * <code>required int32 currentLevel = 1;</code>
       *
       * <pre>
       ** 当前等级 
       * </pre>
       */
      public boolean hasCurrentLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 currentLevel = 1;</code>
       *
       * <pre>
       ** 当前等级 
       * </pre>
       */
      public int getCurrentLevel() {
        return currentLevel_;
      }
      /**
       * <code>required int32 currentLevel = 1;</code>
       *
       * <pre>
       ** 当前等级 
       * </pre>
       */
      public Builder setCurrentLevel(int value) {
        bitField0_ |= 0x00000001;
        currentLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currentLevel = 1;</code>
       *
       * <pre>
       ** 当前等级 
       * </pre>
       */
      public Builder clearCurrentLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:network.message.VipLevelUpNtf)
    }

    static {
      defaultInstance = new VipLevelUpNtf(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:network.message.VipLevelUpNtf)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_message_VipNtf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_message_VipNtf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_message_VipLevelUpNtf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_message_VipLevelUpNtf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nCVip.proto\022\017network.message\032\016CVipInfo." +
      "proto\"3\n\006VipNtf\022)\n\004info\030\001 \002(\0132\033.network." +
      "message.VipNtfInfo\"%\n\rVipLevelUpNtf\022\024\n\014c" +
      "urrentLevel\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          network.message.CVipInfo.getDescriptor(),
        }, assigner);
    internal_static_network_message_VipNtf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_network_message_VipNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_message_VipNtf_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_network_message_VipLevelUpNtf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_network_message_VipLevelUpNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_message_VipLevelUpNtf_descriptor,
        new java.lang.String[] { "CurrentLevel", });
    network.message.CVipInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
